# Етап 1: Збірка Vue.js
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Етап 2: Nginx для статичних файлів
FROM nginx:alpine

# Встановимо gettext (щоб був envsubst)
RUN apk add --no-cache gettext

# Копіюємо зібраний фронт
COPY --from=build /app/dist /usr/share/nginx/html

# Копіюємо шаблон nginx.conf
COPY nginx.conf.template /etc/nginx/conf.d/nginx.conf.template

# Стартовий скрипт (генерує конфіг і запускає nginx)
CMD ["/bin/sh", "-c", "envsubst '$BACKEND_URL $PORT' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
