# Generated by Django 5.2.6 on 2025-09-09 17:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', 'Letters and digits only')])),
                ('image', models.ImageField(upload_to='captchas/')),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'captcha',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Letters and digits only (required)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', 'Only letters and digits allowed')])),
                ('email', models.EmailField(help_text='Valid email format (required)', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('homepage', models.URLField(blank=True, help_text='Valid URL (optional)', null=True, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text with allowed HTML tags (<a>, <code>, <i>, <strong>)', validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('file', models.FileField(blank=True, help_text='Image (JPG/GIF/PNG <=320x240) or TXT (<=100KB)', null=True, upload_to='uploads/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments.user')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
