# Generated by Django 5.2.6 on 2025-09-10 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Captcha',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='default@example.com', help_text='Valid email format (required)', max_length=254, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='home_page',
            field=models.URLField(blank=True, help_text='Valid URL (optional)', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='default@example.com', help_text='Letters and digits only (required)', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', 'Only letters and digits allowed')]),
            preserve_default=False,
        ),
    ]
