# Generated by Django 5.2.6 on 2025-09-23 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_delete_captcha_remove_comment_user_comment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='home_page',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, help_text='Associated user (required)', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Valid email format (required)', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Letters and digits only (required)', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', 'Only letters and digits allowed')]),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at', 'user'], name='comments_created_be8a87_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comments_parent__9f8798_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'email'], name='users_usernam_71eb2e_idx'),
        ),
    ]
